site_name: MAGE_procgen Documentation 
nav:
  - Home: index.md
  - Installation: install.md
  - IGN Data Management: datafiles.md
  - Configuration Files Edition: conf.md
  - Standard Workdlow: workflow.md
  - Assets Management: assets.md
  - Flooding Algorithm: flood.md
  - Dev Documentation: dev.md
theme: readthedocs
plugins:
  - search
  - mkdocstrings
markdown_extensions:
  - admonition
