site_name: WorldWeaver Documentation
nav:
  - Home: index.md
  - Installation: install.md
  - Usage: workflow.md
  - Managing IGN open data: datafiles.md
  - Configuration files: conf.md
  - Managing assets: assets.md
  - Flooding algorithm: flood.md
  - Developer documentation: dev.md
theme: readthedocs
plugins:
  - search
  - mkdocstrings
markdown_extensions:
  - admonition
extra_css:
  - stylesheets/extra.css
